version: "2"

services:
  obd_exporter:
    restart: on-failure
    build:
      context: packages/obd
    volumes:
      - ${OBD_PORT:-/dev/rfcomm0}:/dev/rfcomm0
      - ./packages/obd/obd-monitor.py:/usr/bin/obd-monitor.py:ro
  prometheus:
    image: prom/prometheus:v2.37.0
    restart: on-failure
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - 9090:9090
    volumes:
      - ./packages/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus_data:/prometheus
  mpd:
    restart: on-failure
    user: mpd
    cap_add:
      - SYS_NICE
    build:
      context: packages/mpd
    ports:
      - 8000:8000
    volumes:
      - ./data/mpd/config:/root/.config
      - ./data/mpd/music:/var/lib/mpd/music
      - ./data/mpd/playlists:/var/lib/mpd/playlists
      - ./packages/mpd/mpd.conf:/etc/mpd.conf:ro
  ui:
    restart: on-failure
    user: node
    image: node:16-alpine
    command: ./entrypoint.sh
    working_dir: /usr/src/ui
    volumes:
      - ./packages/ui:/usr/src/ui
  api:
    restart: on-failure
    user: node
    image: node:16-alpine
    command: ./entrypoint.sh
    working_dir: /usr/src/api
    volumes:
      - ./packages/api:/usr/src/api
      - ./data/api/cache:/usr/src/api/cache
    depends_on:
      - mpd
  nginx:
    restart: on-failure
    image: nginx:1-alpine
    ports:
      - 3000:80
    volumes:
      - ./packages/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ui
      - api

volumes:
  prometheus_data:
