version: "2"

services:
  obd_exporter:
    image: ghcr.io/andersevenrud/mycardashpoc-obd:latest
    restart: on-failure
    volumes:
      - ${OBD_PORT:-/dev/rfcomm0}:/dev/rfcomm0
  prometheus:
    image: prom/prometheus:v2.37.0
    restart: on-failure
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - ./packages/prometheus/etc:/etc/prometheus/:ro
      - prometheus_data:/prometheus
  mpd:
    image: ghcr.io/andersevenrud/mycardashpoc-mpd:latest
    restart: on-failure
    user: mpd
    cap_add:
      - SYS_NICE
    ports:
      - 8000:8000
    volumes:
      - ./data/mpd/config:/root/.config
      - ./data/mpd/music:/var/lib/mpd/music
      - ./data/mpd/playlists:/var/lib/mpd/playlists
      - ./packages/mpd/mpd.conf:/etc/mpd.conf:ro
  ui:
    image: ghcr.io/andersevenrud/mycardashpoc-ui:latest
    restart: on-failure
  api:
    image: ghcr.io/andersevenrud/mycardashpoc-api:latest
    restart: on-failure
    user: node
    volumes:
      - ./data/api/cache:/usr/src/api/cache
    depends_on:
      - mpd
  nginx:
    restart: on-failure
    image: nginx:1-alpine
    volumes:
      - ./packages/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - ui
      - api

volumes:
  prometheus_data:
