name: Docker Image Publish
on:
  push:
    branches:
      - main
jobs:
  publish_api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        docker buildx build \
          -t ghcr.io/${{ github.repository_owner }}/mycardashpoc-api:latest \
          -f packages/api/Dockerfile \
          --push \
          --platform=linux/arm64,linux/amd64 packages/api
  publish_ui:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        docker buildx build \
          -t ghcr.io/${{ github.repository_owner }}/mycardashpoc-ui:latest \
          -f packages/ui/Dockerfile \
          --push \
          --platform=linux/arm64,linux/amd64 packages/ui
  publish_obd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        docker buildx build \
          -t ghcr.io/${{ github.repository_owner }}/mycardashpoc-obd:latest \
          -f packages/obd/Dockerfile \
          --push \
          --platform=linux/arm64,linux/amd64 packages/obd
  publish_mpd:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        docker buildx build \
          -t ghcr.io/${{ github.repository_owner }}/mycardashpoc-mpd:latest \
          -f packages/mpd/Dockerfile \
          --push \
          --platform=linux/arm64,linux/amd64 packages/mpd
